<?php
/**
* Country List Language File
* Version: 1.0
* Date: 31/10/2006
*
* Array keys refer to the ID number that is saved in the database
*
*/

$_country_lang["1"] = 'Afganistan'; // Afghanistan
$_country_lang["2"] = 'Albaania'; // Albania
$_country_lang["3"] = 'Alžīrija'; // Algeria
$_country_lang["4"] = 'Amerikas Samoa'; // American Samoa
$_country_lang["5"] = 'Andora'; // Andorra
$_country_lang["6"] = 'Angola'; // Angola
$_country_lang["7"] = 'Angvila'; // Anguilla
$_country_lang["8"] = 'Antarktika'; // Antarctica
$_country_lang["9"] = 'Antigua un Barbuda'; // Antigua and Barbuda
$_country_lang["10"] = 'Argentīna'; // Argentina
$_country_lang["11"] = 'Armēnija'; // Armenia
$_country_lang["12"] = 'Aruba'; // Aruba
$_country_lang["13"] = 'Austrālija'; // Australia
$_country_lang["14"] = 'Austrija'; // Austria
$_country_lang["15"] = 'Azerbaidžāna'; // Azerbaijan
$_country_lang["16"] = 'Bahamas'; // Bahamas
$_country_lang["17"] = 'Bahreina'; // Bahrain
$_country_lang["18"] = 'Bangladeša'; // Bangladesh
$_country_lang["19"] = 'Barbadosa'; // Barbados
$_country_lang["20"] = 'Valgevene'; // Belarus
$_country_lang["21"] = 'Beļģija'; // Belgium
$_country_lang["22"] = 'Belīze'; // Belize
$_country_lang["23"] = 'Benin'; // Benin
$_country_lang["24"] = 'Bermuda'; // Bermuda
$_country_lang["25"] = 'Butāna'; // Bhutan
$_country_lang["26"] = 'Bolīvija'; // Bolivia
$_country_lang["27"] = 'Bosnija Hertsegovina'; // Bosnia and Herzegowina
$_country_lang["28"] = 'Botswana'; // Botswana
$_country_lang["29"] = 'Bouvet sala'; // Bouvet Island
$_country_lang["30"] = 'Brazīlija'; // Brazil
$_country_lang["31"] = 'Britu Indijas Okeānija'; // British Indian Ocean Territory
$_country_lang["32"] = 'Bruneja'; // Brunei Darussalam
$_country_lang["33"] = 'Bulgārija'; // Bulgaria
$_country_lang["34"] = 'Burkina Faso'; // Burkina Faso
$_country_lang["35"] = 'Burundi'; // Burundi
$_country_lang["36"] = 'Kambodža'; // Cambodia
$_country_lang["37"] = 'Kamerūna'; // Cameroon
$_country_lang["38"] = 'Kanāda'; // Canada
$_country_lang["39"] = 'Keipverde'; // Cape Verde
$_country_lang["40"] = 'Kaimanu salas'; // Cayman Islands
$_country_lang["41"] = 'Centrālāfrikas Republika'; // Central African Republic
$_country_lang["42"] = 'Cada'; // Chad
$_country_lang["43"] = 'Cīle'; // Chile
$_country_lang["44"] = 'Ķīna'; // China
$_country_lang["45"] = 'Ziemassvētku salas'; // Christmas Island
$_country_lang["46"] = 'Kokosa salas'; // Cocos (Keeling) Islands
$_country_lang["47"] = 'Kolumbija'; // Colombia
$_country_lang["48"] = 'Komorosa'; // Comoros
$_country_lang["49"] = 'Kongo Republika'; // Congo
$_country_lang["50"] = 'Kuka salas'; // Cook Islands
$_country_lang["51"] = 'Kosta Rika'; // Costa Rica
$_country_lang["52"] = 'Koste Ivora'; // Cote D&#39;Ivoire
$_country_lang["53"] = 'Horvātija'; // Croatia
$_country_lang["54"] = 'Kuba'; // Cuba
$_country_lang["55"] = 'Kipra'; // Cyprus
$_country_lang["56"] = 'Čehijas Republika'; // Czech Republic
$_country_lang["57"] = 'Dānija'; // Denmark
$_country_lang["58"] = 'Džiboti'; // Djibouti
$_country_lang["59"] = 'Dominika'; // Dominica
$_country_lang["60"] = 'Dominikāņu Republika'; // Dominican Republic
$_country_lang["61"] = 'Austrum Timora'; // East Timor
$_country_lang["62"] = 'Ekvadora'; // Ecuador
$_country_lang["63"] = 'Ēģipte'; // Egypt
$_country_lang["64"] = 'Salvadora'; // El Salvador
$_country_lang["65"] = 'Ekvatoriāl-Gvineja'; // Equatorial Guinea
$_country_lang["66"] = 'Eritrea'; // Eritrea
$_country_lang["67"] = 'Igaunija'; // Estonia
$_country_lang["68"] = 'Etiopija'; // Ethiopia
$_country_lang["69"] = 'Falklendu salas'; // Falkland Islands (Malvinas)
$_country_lang["70"] = 'Fāreja salas'; // Faroe Islands
$_country_lang["71"] = 'Fidži'; // Fiji
$_country_lang["72"] = 'Somija'; // Finland
$_country_lang["73"] = 'Francija'; // France
$_country_lang["74"] = 'Franču Metroplitēns'; // France, Metropolitan
$_country_lang["75"] = 'Franču Gvana'; // French Guiana
$_country_lang["76"] = 'Franču Polinēzija'; // French Polynesia
$_country_lang["77"] = 'Franču Dienvidi'; // French Southern Territories
$_country_lang["78"] = 'Gabona'; // Gabon
$_country_lang["79"] = 'Gambija'; // Gambia
$_country_lang["80"] = 'Gruzija'; // Georgia
$_country_lang["81"] = 'Vācija'; // Germany
$_country_lang["82"] = 'Gana'; // Ghana
$_country_lang["83"] = 'Gibraltārs'; // Gibraltar
$_country_lang["84"] = 'Grieķija'; // Greece
$_country_lang["85"] = 'Grenlande'; // Greenland
$_country_lang["86"] = 'Grenāde'; // Grenada
$_country_lang["87"] = 'Guadelupe'; // Guadeloupe
$_country_lang["88"] = 'Guama'; // Guam
$_country_lang["89"] = 'Gvatemala'; // Guatemala
$_country_lang["90"] = 'Gvineja'; // Guinea
$_country_lang["91"] = 'Gvineja-bisso'; // Guinea-bissau
$_country_lang["92"] = 'Guijana'; // Guyana
$_country_lang["93"] = 'Haiti'; // Haiti
$_country_lang["94"] = 'Heard ja McDonald'; // Heard and Mc Donald Islands
$_country_lang["95"] = 'Hondurasa'; // Honduras
$_country_lang["96"] = 'Hong Konga'; // Hong Kong
$_country_lang["97"] = 'Ungārija'; // Hungary
$_country_lang["98"] = 'Islande'; // Iceland
$_country_lang["99"] = 'Indija'; // India
$_country_lang["100"] = 'Indonēzija'; // Indonesia
$_country_lang["101"] = 'Irāna'; // Iran (Islamic Republic of)
$_country_lang["102"] = 'Irāka'; // Iraq
$_country_lang["103"] = 'Īrija'; // Ireland
$_country_lang["104"] = 'Izraēla'; // Israel
$_country_lang["105"] = 'Itālija'; // Italy
$_country_lang["106"] = 'Jamaika'; // Jamaica
$_country_lang["107"] = 'Japāna'; // Japan
$_country_lang["108"] = 'Džordānija'; // Jordan
$_country_lang["109"] = 'Kazahstāna'; // Kazakhstan
$_country_lang["110"] = 'Kenija'; // Kenya
$_country_lang["111"] = 'Kiribati'; // Kiribati
$_country_lang["112"] = 'Korejas Demoktrātiskā Republika'; // Korea, Democratic People&#39;s Republic of
$_country_lang["113"] = 'Korejas Republika'; // Korea, Republic of
$_country_lang["114"] = 'Kuveita'; // Kuwait
$_country_lang["115"] = 'Kirgīzija'; // Kyrgyzstan
$_country_lang["116"] = 'Laosas Demoktrātiskā Republika'; // Lao People&#39;s Democratic Republic
$_country_lang["117"] = 'Latvija'; // Latvia
$_country_lang["118"] = 'Lībija'; // Lebanon
$_country_lang["119"] = 'Lesoto'; // Lesotho
$_country_lang["120"] = 'Libērija'; // Liberia
$_country_lang["121"] = 'Libānas Arābu Maharadžija'; // Libyan Arab Jamahiriya
$_country_lang["122"] = 'Lihtenšteina'; // Liechtenstein
$_country_lang["123"] = 'Lietuva'; // Lithuania
$_country_lang["124"] = 'Luksemburga'; // Luxembourg
$_country_lang["125"] = 'Makau'; // Macau
$_country_lang["126"] = 'Maķedonijas Republika'; // Macedonia, The Former Yugoslav Republic of
$_country_lang["127"] = 'Madagaskāra'; // Madagascar
$_country_lang["128"] = 'Malavi'; // Malawi
$_country_lang["129"] = 'Malaizija'; // Malaysia
$_country_lang["130"] = 'Malvīdi'; // Maldives
$_country_lang["131"] = 'Malī'; // Mali
$_country_lang["132"] = 'Malta'; // Malta
$_country_lang["133"] = 'Maršala Salas'; // Marshall Islands
$_country_lang["134"] = 'Martinika'; // Martinique
$_country_lang["135"] = 'Mauritānija'; // Mauritania
$_country_lang["136"] = 'Maurīcijas'; // Mauritius
$_country_lang["137"] = 'Maijote'; // Mayotte
$_country_lang["138"] = 'Meksika'; // Mexico
$_country_lang["139"] = 'Mikronēzija'; // Micronesia, Federated States of
$_country_lang["140"] = 'Moldāvijas Republika'; // Moldova, Republic of
$_country_lang["141"] = 'Monako'; // Monaco
$_country_lang["142"] = 'Mongolija'; // Mongolia
$_country_lang["241"] = 'Montenegro'; //Montenegro
$_country_lang["143"] = 'Monserata'; // Montserrat
$_country_lang["144"] = 'Maroka'; // Morocco
$_country_lang["145"] = 'Mozambika'; // Mozambique
$_country_lang["146"] = 'Birma'; // Myanmar
$_country_lang["147"] = 'Namībija'; // Namibia
$_country_lang["148"] = 'Nauru'; // Nauru
$_country_lang["149"] = 'Nepāla'; // Nepal
$_country_lang["150"] = 'Holande'; // Netherlands
$_country_lang["151"] = 'Holandes Antiļas'; // Netherlands Antilles
$_country_lang["152"] = 'Jaun-Kaledonija'; // New Caledonia
$_country_lang["153"] = 'Jaunzēlande'; // New Zealand
$_country_lang["154"] = 'Nikaragva'; // Nicaragua
$_country_lang["155"] = 'Nigēra'; // Niger
$_country_lang["156"] = 'Nigērija'; // Nigeria
$_country_lang["157"] = 'Niue'; // Niue
$_country_lang["158"] = 'Norfolk Sala'; // Norfolk Island
$_country_lang["159"] = 'Ziemieļ Marianas Salas'; // Northern Mariana Islands
$_country_lang["160"] = 'Norvēģija'; // Norway
$_country_lang["161"] = 'Omāna'; // Oman
$_country_lang["162"] = 'Pakistāna'; // Pakistan
$_country_lang["163"] = 'Palau'; // Palau
$_country_lang["164"] = 'Panama'; // Panama
$_country_lang["165"] = 'Pappua Jaun Gvineja'; // Papua New Guinea
$_country_lang["166"] = 'Paragvaja'; // Paraguay
$_country_lang["167"] = 'Perū'; // Peru
$_country_lang["168"] = 'Filipīnas'; // Philippines
$_country_lang["169"] = 'Pitkerna'; // Pitcairn
$_country_lang["170"] = 'Polija'; // Poland
$_country_lang["171"] = 'Portugāle'; // Portugal
$_country_lang["172"] = 'Puerto Rico'; // Puerto Rico
$_country_lang["173"] = 'Katāra'; // Qatar
$_country_lang["174"] = 'Reunion'; // Reunion
$_country_lang["175"] = 'Rumānija'; // Romania
$_country_lang["176"] = 'Krievijas Federācija'; // Russian Federation
$_country_lang["177"] = 'Ruanda'; // Rwanda
$_country_lang["178"] = 'Saint Kitts un Nevis'; // Saint Kitts and Nevis
$_country_lang["179"] = 'Svētā Lūcija'; // Saint Lucia
$_country_lang["180"] = 'Svētā Vinsenta un Grenadīnas'; // Saint Vincent and the Grenadines
$_country_lang["181"] = 'Samoja'; // Samoa
$_country_lang["182"] = 'San Marīno'; // San Marino
$_country_lang["183"] = 'Sao Tome un Príncipe'; // Sao Tome and Principe
$_country_lang["184"] = 'Saudu Arābija'; // Saudi Arabia
$_country_lang["185"] = 'Senegāla'; // Senegal
$_country_lang["240"] = 'Serbija'; //Serbia
$_country_lang["186"] = 'Seišelas'; // Seychelles
$_country_lang["187"] = 'Sierra Leone'; // Sierra Leone
$_country_lang["188"] = 'Singapūra'; // Singapore
$_country_lang["189"] = 'Slovākijas Republika'; // Slovakia (Slovak Republic)
$_country_lang["190"] = 'Slovēnija'; // Slovenia
$_country_lang["191"] = 'Salomonas Salas'; // Solomon Islands
$_country_lang["192"] = 'Somālija'; // Somalia
$_country_lang["193"] = 'Dienvidāfrikas Republika'; // South Africa
$_country_lang["194"] = 'South Georgia and the South Sandwich Islands'; // South Georgia and the South Sandwich Islands
$_country_lang["195"] = 'Spānija'; // Spain
$_country_lang["196"] = 'Šrilanka'; // Sri Lanka
$_country_lang["197"] = 'Svētā Helēna'; // St. Helena
$_country_lang["198"] = 'Saint-Pierre ja Miquelon'; // St. Pierre and Miquelon
$_country_lang["199"] = 'Sudāna'; // Sudan
$_country_lang["200"] = 'Suriname'; // Suriname
$_country_lang["201"] = 'Svalbard ja Jan Mayeni Saared'; // Svalbard and Jan Mayen Islands
$_country_lang["202"] = 'Svazilenda'; // Swaziland
$_country_lang["203"] = 'Zviedrija'; // Sweden
$_country_lang["204"] = 'Šveice'; // Switzerland
$_country_lang["205"] = 'Sīrijas Arābu Republika'; // Syrian Arab Republic
$_country_lang["206"] = 'Taivāna'; // Taiwan
$_country_lang["207"] = 'Tadžikistāna'; // Tajikistan
$_country_lang["208"] = 'Tanzānijas Republika'; // Tanzania, United Republic of
$_country_lang["209"] = 'Taizeme'; // Thailand
$_country_lang["210"] = 'Togo'; // Togo
$_country_lang["211"] = 'Tokelau'; // Tokelau
$_country_lang["212"] = 'Tonga'; // Tonga
$_country_lang["213"] = 'Trinidada un Tobago'; // Trinidad and Tobago
$_country_lang["214"] = 'Tunisija'; // Tunisia
$_country_lang["215"] = 'Turcija'; // Turkey
$_country_lang["216"] = 'Turkmenistāna'; // Turkmenistan
$_country_lang["217"] = 'Turks un Caico Salas'; // Turks and Caicos Islands
$_country_lang["218"] = 'Tuvalu'; // Tuvalu
$_country_lang["219"] = 'Uganda'; // Uganda
$_country_lang["220"] = 'Ukraina'; // Ukraine
$_country_lang["221"] = 'Apvienotie Arābu Emirāti'; // United Arab Emirates
$_country_lang["222"] = 'Lielbritānija'; // United Kingdom
$_country_lang["223"] = 'Savienotās Valstis'; // United States
$_country_lang["224"] = 'Savienotās Valstis Ārējās Piederošās Salas'; // United States Minor Outlying Islands
$_country_lang["225"] = 'Urugvaja'; // Uruguay
$_country_lang["226"] = 'Uzbekistāna'; // Uzbekistan
$_country_lang["227"] = 'Vanuatu'; // Vanuatu
$_country_lang["228"] = 'Vatikāns'; // Vatican City State (Holy See)
$_country_lang["229"] = 'Venecuēla'; // Venezuela
$_country_lang["230"] = 'Vjetnama'; // Viet Nam
$_country_lang["231"] = 'Virdžīnijas Salas'; // Virgin Islands (British)
$_country_lang["232"] = 'Virdžīnijas Salas, ASV'; // Virgin Islands (U.S.)
$_country_lang["233"] = 'Wallis un Futuna'; // Wallis and Futuna Islands
$_country_lang["234"] = 'Rietum Sahāra'; // Western Sahara
$_country_lang["235"] = 'Jemena'; // Yemen
$_country_lang["236"] = 'Serbija un Montenegro'; // DEPRECATED: kept for backwards compatibility, Serbia and Montenegro
$_country_lang["237"] = 'Kongo Demokrātiskā Republika'; // Congo, Democratic Republic of the
$_country_lang["238"] = 'Zambija'; // Zambia
$_country_lang["239"] = 'Zimbabve'; // Zimbabwe
?>
